name: getx_translator
description: A command-line application for generating language strings file for Getx Flutter. Easy translation with google sheet for Getx.
version: 1.0.1
homepage: https://github.com/bikram0000/getx_translator
repository: https://github.com/bikram0000/getx_translator

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.5
  yaml: ^3.1.1
  args: ^2.3.1
  logger: ^1.1.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


